POST http://localhost:3000/api/posts 
Content-Type: application/json

{
    "title": "Meu terceiro post",
    "content": "conteúdo do post",
    "userID": 9999
}

### 

GET http://localhost:3000/api/posts

### 

DELETE http://localhost:3000/api/posts/6
